name: Publish Packages to GitHub

on:
  workflow_dispatch:
    
jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Clone Code
      uses: actions/checkout@v3
      with:
        submodules: false
        fetch-depth: 0
    
    - name: Setup Visual Studio Command Prompt
      uses: microsoft/setup-msbuild@v2.0.0
      
    - name: Build WPF
      run: |
        msbuild /restore /t:Build src\Esri.Calcite.WPF\Esri.Calcite.WPF.csproj /p:Configuration=Release
        
    - name: Build WinUI
      run: |
        msbuild /restore /t:Build src\Esri.Calcite.WinUI\Esri.Calcite.WinUI.csproj /p:Configuration=Release
        
    - name: Build MAUI
      run: |
        msbuild /restore /t:Build src\Esri.Calcite.Maui\Esri.Calcite.Maui.csproj /p:Configuration=Release

    - name: Publish
      run: |
        dotnet nuget push artifacts\NuGet\Release\*.nupkg --api-key  ${{ secrets.GithubPushPackagesSecret }} --source https://nuget.pkg.github.com/dotMorten/index.json 
